"""
RiskHub — ``alerts_log`` Collection Model
==========================================
Schema reference:  Database Architecture Document v1.0  §4.2

Design notes:
* ``trigger_context`` embeds a snapshot of the exact evidence that fired
  the rule — survives even if the source trade records are later purged.
* ``rate_limit_key`` is a composite string (rule_id + user_id) used
  for 30-minute rate-limit checks before firing a new alert.
* ``expires_at`` drives a TTL index (``expireAfterSeconds: 0``)
  allowing per-document retention policies (30 days default,
  90 days for critical alerts in future).
* ``related_trade_ids`` stores ObjectId references — not embedded
  copies — so the frontend can deep-link to specific trades.
"""

from __future__ import annotations

from datetime import datetime, timedelta
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field

from .base import MongoBaseDocument, PyObjectId, DecimalStr


# ── Enums ────────────────────────────────────────────────────────────────

class AlertSeverity(str, Enum):
    CRITICAL = "critical"
    WARNING = "warning"
    CAUTION = "caution"
    NOTICE = "notice"


class AlertCategory(str, Enum):
    BEHAVIORAL = "behavioral"
    LIQUIDATION = "liquidation"
    PORTFOLIO = "portfolio"


# ── Sub-documents ────────────────────────────────────────────────────────

class TriggerContext(BaseModel):
    """
    Snapshot of the exact data that caused the Quant Engine rule to fire.

    Each rule ID may populate different fields — e.g. BHV-001 (Revenge
    Trading) populates ``loss_trade_id`` + ``trigger_trade_id``, while
    BHV-005 (Concentration Risk) populates ``concentrated_asset`` +
    ``concentration_pct``.

    All fields are optional because the schema must accommodate every rule.
    """
    rule_id: Optional[str] = None

    # Revenge Trading (BHV-001) context
    loss_trade_id: Optional[PyObjectId] = None      # Ref → trade_history._id
    loss_amount_usd: Optional[DecimalStr] = None
    loss_pct_equity: Optional[DecimalStr] = None
    trigger_trade_id: Optional[PyObjectId] = None    # Ref → trade_history._id (new position)
    trigger_leverage: Optional[int] = None
    trigger_symbol: Optional[str] = None
    minutes_since_loss: Optional[int] = None
    threshold_minutes: Optional[int] = None

    # Overtrading (BHV-002) context
    trade_count_in_window: Optional[int] = None
    window_minutes: Optional[int] = None

    # Excessive Leverage (BHV-003) context
    detected_leverage: Optional[int] = None

    # Max Drawdown (BHV-004) context
    drawdown_pct: Optional[DecimalStr] = None
    drawdown_threshold_pct: Optional[DecimalStr] = None

    # Concentration Risk (BHV-005) context
    concentrated_asset: Optional[str] = None
    concentration_pct: Optional[DecimalStr] = None

    # Common
    exchange_id: Optional[str] = None


class DeliveryStatus(BaseModel):
    """Tracks whether the alert was successfully pushed to the user."""
    websocket_sent: bool = False
    websocket_sent_at: Optional[datetime] = None
    email_sent: bool = False
    email_sent_at: Optional[datetime] = None


# ── Root document ────────────────────────────────────────────────────────

class AlertsLogDocument(MongoBaseDocument):
    """
    Root Pydantic model for the ``alerts_log`` MongoDB collection.

    One document per behavioral alert event generated by the Quant Engine.
    """

    # Partition key
    user_id: PyObjectId

    # Rule reference
    rule_id: str                            # e.g. "BHV-001"
    rule_name: str                          # human-readable, e.g. "Revenge Trading"
    rule_version: str = "1.0"

    # Alert classification
    severity: AlertSeverity
    category: AlertCategory = AlertCategory.BEHAVIORAL

    # Alert content
    title: str
    message: str
    recommendation: Optional[str] = None

    # Triggering context (Quant Engine evidence)
    trigger_context: Optional[TriggerContext] = None

    # Related trades (ObjectId array of references)
    related_trade_ids: list[PyObjectId] = Field(default_factory=list)

    # Delivery & Acknowledgement
    delivery: DeliveryStatus = Field(default_factory=DeliveryStatus)
    is_read: bool = False
    read_at: Optional[datetime] = None
    is_dismissed: bool = False
    dismissed_at: Optional[datetime] = None

    # Rate limiting
    rate_limit_key: Optional[str] = None    # composite: "BHV-001::user_<id>::"
    rate_limit_window_start: Optional[datetime] = None

    # Timestamps
    triggered_at: datetime = Field(default_factory=datetime.utcnow)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.utcnow() + timedelta(days=30)
    )

    # Metadata
    schema_version: int = 1
